hmcts/aks-module-kubernetes

.gitignore, 01-inputs-required.tf, 03-interpolated-defaults.tf, 10-kubernetes-inputs.tf, 12-kubernetes-cluster.tf
Name refactor
```
[ ] Yes
[ ] No
```
=> Name refactor

00-init.tf, 01-inputs-required.tf, 03-interpolated-defaults.tf, 12-kubernetes-cluster.tf, local.tf
https://tools.hmcts.net/jira/browse/DTSPO-171
Push k8s logs to shared log(hmcts-<env>) analytics workspace
[ ] Yes
[ x] No
```
=> DTSPO-171: modified log analytics workspace

10-kubernetes-inputs.tf, 12-kubernetes-cluster.tf
It's removed as an addon in 1.19
=> Remove dashboard

00-init.tf, 01-inputs-required.tf, 10-kubernetes-inputs.tf, 12-kubernetes-cluster.tf, acr-permissions.tf
https://tools.hmcts.net/jira/browse/DTSPO-22
=> DTSPO-22 User assigned identity

00-init.tf, 10-kubernetes-inputs.tf, 12-kubernetes-cluster.tf
=> DTSPO-2168 Add Windows NodePool to Sandbox

12-kubernetes-cluster.tf
dtspo:2396 Cluster upgrade. Work around for terraform-provider-azurerm/issues/10406
=> dtspo:2396 Cluster upgrade

12-kubernetes-cluster.tf
dtspo:2396. Reverting Cluster upgrade. Work around for terraform-provider-azurerm/issues/10406
=> dtspo:2396 Reverting cluster upgrade

12-kubernetes-cluster.tf
dtspo:2396.  Cluster upgrade. Explicitly adding node pool version
=> dtspo:2396 Cluster upgrade: Explicitly adding node pool version

03-interpolated-defaults.tf
=> DTSPO-3207-Fix-perftest-deploy-pipeline

12-kubernetes-cluster.tf
=> DTSPO-3207-changing-reference-to-local-env

12-kubernetes-cluster.tf
=> Fixing regression issues

12-kubernetes-cluster.tf
=> fixing duplicate local variables

00-init.tf, 12-kubernetes-cluster.tf, outputs.tf
Add output of cluster(s) for new devops pipeline
```
[ ] Yes
[X] No
```
=> Add output of cluster(s) for new devops pipeline

00-init.tf, 12-kubernetes-cluster.tf, outputs.tf, provider.tf
=> DTSPO-1032 multi cluster

12-kubernetes-cluster.tf
https://tools.hmcts.net/jira/browse/DTSPO-2879
Adding new VM Contributor role assignment to allow cluster identity to access jenkins disk resource group
```
[ ] Yes
[ x ] No
```
=> DTSPO-2879 - Disks RG role assignment

12-kubernetes-cluster.tf
https://tools.hmcts.net/jira/browse/DTSPO-382
Update with common tags for aks clusters
```
[ ] Yes
[x] No
```
=> DTSPO-382: Tagging resources with common tags

12-kubernetes-cluster.tf
=> DTSPO-2879  Jenkins: Using Cluster mi instead

12-kubernetes-cluster.tf
=> DTSPO-2879  Jenkins: Using Cluster principal id for  mi instead

03-interpolated-defaults.tf, 10-kubernetes-inputs.tf
=> fix for azure control vault access

12-kubernetes-cluster.tf
- Look for mode flag
```
[ ] Yes
[x] No
```
=> DTSPO-4675 - add ability to set mode to system for additional np's

00-init.tf
Upgrade AzureRM to 2.76
```
[ ] Yes
[x] No
```
=> Upgrade AzureRM to 2.76

00-init.tf, 12-kubernetes-cluster.tf
Upgraded azurerm provider to the latest version
```
[ ] Yes
[x] No
```
=> DTSPO-7029 - upgrade provider to 3.0.2

01-inputs-required.tf, 12-kubernetes-cluster.tf, outputs.tf
https://tools.hmcts.net/jira/browse/DTSPO-7031
moving to aks-sds-deploy so that roles are not tied to cluster lifecycle
```
[ ] Yes
[ ] No
```
=> DTSPO-7031 Move node resources out of module

12-kubernetes-cluster.tf, outputs.tf
https://tools.hmcts.net/jira/browse/DTSPO-7031
The user assigned identity ID is 'id' as per
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/user_assigned_identity#attributes-reference
```
[ ] Yes
[x] No
```
=> DTSPO-7031 Amend User Assigned Identity ID

00-init.tf
Upgrading tf version to v1.2.2 and azurerm provider to 3.10.0
```
[ ] Yes
[x] No
```
=> DTSPO-8276 - upgrade terraform and azure provider

00-init.tf, 01-inputs-required.tf, 12-kubernetes-cluster.tf
Added a toggle for the CSI Driver add-on so that we can start deploying the add-on.
```
[ ] Yes
[x] No
```
=> DTSPO-9539 - add toggle for csi driver add-on

00-init.tf, 01-inputs-required.tf, 12-kubernetes-cluster.tf, outputs.tf
https://tools.hmcts.net/jira/browse/DTSPO-10591
Creates role assignment for env MI and a federated identity credential for Azure Service Operator
Tested here  - https://dev.azure.com/hmcts/CNP/_build/results?buildId=289486&view=logs&j=9529ead6-39ae-5319-1740-9d2035106bd6&t=89b2e481-5d95-5be1-d64b-e101e3d88784
```
[ ] Yes
[X] No
```
=> DTSPO-10591 OIDC-issuer-url

01-inputs-required.tf, 12-kubernetes-cluster.tf
Add update timeout to additional_node_pools to reflect GA updates
```
[ ] Yes
[x] No
```
=> Add update timeout to additional_node_pools to reflect GA updates

01-inputs-required.tf, 12-kubernetes-cluster.tf, aks-auto-shutdown-permissions.tf
[DTSPO-11424](https://tools.hmcts.net/jira/browse/DTSPO-11424)
Add Role Assignment and Managed Identity for AKS Auto Shutdown
```
[ ] Yes
[X] No
```
=> DTSPO-11424 - Add Role Assignment and Managed Identity

01-inputs-required.tf, 12-kubernetes-cluster.tf
I will wait to merge until CFT repo has been updated
- remove unneeded depends_on inputs
- require disks resource group id to be passed via an input 
```
[ ] Yes
[x] No
```
=> DTSPO-11790 - disk resource group var

01-inputs-required.tf, update-checker-permissions.tf
https://tools.hmcts.net/jira/browse/DTSPO-13486
Parameterising version checker app role, so it can be overridden.
```
[ ] Yes
[x] No
```
=> parameterised version checker app role

01-inputs-required.tf, 12-kubernetes-cluster.tf
- [X ] commit messages are meaningful and follow good commit message guidelines
Removed feature flags workload_identity_enabled and service_operator_settings_enabled as its enabled from all the sds and cft environments.
```
[ X ] Yes
[ ] No
```
=> removed flags

12-kubernetes-cluster.tf
DTSPO-13636
Change retention days to 0, as Microsoft no longer allows this to be set, as per this discussion https://github.com/hashicorp/terraform-provider-azurerm/issues/23051
```
[ ] Yes
[ x ] No
```
=> Remove retention policy for AllMetrics

12-kubernetes-cluster.tf
=> DTSPO-15105 update additional pool arguments

01-inputs-required.tf, 10-kubernetes-inputs.tf, 12-kubernetes-cluster.tf
https://tools.hmcts.net/jira/browse/DTSPO-14865
Updated cluster file to include node_os_channel_upgrade 
Updated variables to accommodate node os upgrade flag
=> DTSPO-14865-replace-kured

12-kubernetes-cluster.tf
https://tools.hmcts.net/jira/browse/DTSPO-15799
- Needed to fix blocking issue from the Jira above
=> Add eviction policy for spotinstance nodepool

10-kubernetes-inputs.tf, 12-kubernetes-cluster.tf
https://tools.hmcts.net/jira/browse/DTSPO-14865
added dynamic block to add node os maintenance window to sbox only
=> DTSPO-14865-replace-kured-v2

10-kubernetes-inputs.tf, 12-kubernetes-cluster.tf
https://tools.hmcts.net/jira/browse/DTSPO-14865
restricted maintenance window for prod use and updated condition
=> DTSPO-14865: update maintenance window config for prod usage

12-kubernetes-cluster.tf
https://tools.hmcts.net/jira/browse/DTSPO-16590
Fix Destroy 
https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=558436&view=logs&j=9529ead6-39ae-5319-1740-9d2035106bd6&t=89b2e481-5d95-5be1-d64b-e101e3d88784&l=615
=> DTSPO-16590 - fix destroy

12-kubernetes-cluster.tf
add max surge under default node pool
=> add max surge in default node pool block
